import{a as d,S as p,i as n}from"./assets/vendor-BzajH6aU.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const g="https://pixabay.com/api/",c=new URLSearchParams({key:"46809493-025d46e6636e036ef2e71f554",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,page:1,per_page:15});async function h(o){return c.set("q",o),(await d(`${g}?${c}`)).data}function y(o){return o.map(({webformatURL:r,largeImageURL:s,tags:i,likes:e,views:t,comments:a,downloads:u})=>`
        
        <li class="img-card">
            <a class="gallery-link" href="${s}"><img class="img" src="${r}" alt="${i}" width=360 height=200></a>
           <div class="text-container">
           <p class="text">Likes:</br>${e}</p>
                <p class="text">Downloads:</br>${u}</p>
                <p class="text">Views:</br>${t}</p>
                <p class="text">Comments:</br>${a}</p>
           </div></li>`).join("")}const L=new p(".img-card a",{captionsData:"alt",captionDelay:250,overlayOpacity:.8,widthRatio:.9,heigtRatio:.9}),m=document.querySelector(".search-form"),l=document.querySelector(".img-list"),f=document.querySelector(".span");document.querySelector(".load");m.addEventListener("submit",b);async function b(o){o.preventDefault(),l.innerHTML="";const r=o.target.elements.imgname.value.trim();if(r==="")n.show({title:"Please,",message:"fill the field",titleColor:"#fff",messageColor:"#fff",messageSize:"16px",backgroundColor:"#ef4040",position:"center"});else try{f.classList.add("loader");const s=await h(r);s.hits.length===0&&n.show({title:"Sorry,",message:"there are no images matching your search query. Please try again!",titleColor:"#fff",messageColor:"#fff",messageSize:"16px",backgroundColor:"#ef4040",position:"center"}),l.innerHTML=y(s.hits),m.reset(),L.refresh()}catch{n.show({message:"Error",titleColor:"#fff",messageColor:"#fff",messageSize:"16px",backgroundColor:"#ef4040",position:"center"})}finally{f.classList.remove("loader")}}
//# sourceMappingURL=index.js.map
