import{a as y,S as L,i as n}from"./assets/vendor-BzajH6aU.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const b="https://pixabay.com/api/";async function w(r,t=1,a=15){const s=new URLSearchParams({key:"46809493-025d46e6636e036ef2e71f554",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:a});return(await y(`${b}?${s}`)).data}function S(r){return r.map(({webformatURL:t,largeImageURL:a,tags:s,likes:e,views:o,comments:i,downloads:h})=>`
        
        <li class="img-card">
            <a class="gallery-link" href="${a}"><img class="img" src="${t}" alt="${s}" width=360 height=200></a>
           <div class="text-container">
           <p class="text">Likes:</br>${e}</p>
                <p class="text">Downloads:</br>${h}</p>
                <p class="text">Views:</br>${o}</p>
                <p class="text">Comments:</br>${i}</p>
           </div></li>`).join("")}const C=new L(".img-card a",{captionsData:"alt",captionDelay:250,overlayOpacity:.8,widthRatio:.9,heigtRatio:.9}),u=document.querySelector(".search-form"),g=document.querySelector(".img-list"),m=document.querySelector(".span"),c=document.querySelector(".load");u.addEventListener("submit",v);c.addEventListener("click",x);let f=300;const d=15;let l="";async function v(r){if(r.preventDefault(),g.innerHTML="",f=1,l=r.target.elements.imgname.value.trim(),l===""){n.show({title:"Please,",message:"fill the field",titleColor:"#fff",messageColor:"#fff",messageSize:"16px",backgroundColor:"#ef4040",position:"center"});return}await p(l)}async function p(r){try{c.classList.remove("load-more"),m.classList.add("loader");const t=await w(r,f,d);if(t.hits.length===0){n.show({title:"Sorry,",message:"there are no images matching your search query. Please try again!",titleColor:"#fff",messageColor:"#fff",messageSize:"16px",backgroundColor:"#ef4040",position:"center"});return}g.innerHTML+=S(t.hits),c.classList.add("load-more"),u.reset(),C.refresh(),(t.hits.length<d||f>Math.ceil(t.totalHits/d))&&(c.classList.remove("load-more"),n.show({message:"We're sorry, but you've reached the end of search results.",titleColor:"#fff",messageColor:"#fff",messageSize:"16px",backgroundColor:"#ef4040",position:"center"}))}catch{n.show({message:"Error",titleColor:"#fff",messageColor:"#fff",messageSize:"16px",backgroundColor:"#ef4040",position:"center"})}finally{m.classList.remove("loader")}}async function x(){f++,await p(l);const t=document.querySelector(".img-card").getBoundingClientRect().height;window.scrollBy({left:0,top:t*3,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
